# -- Path setup --------------------------------------------------------------

import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = 'EnergySystemModels Tutorial'
author = 'Zoheir HADID'
copyright = f'{datetime.now().year}, {author}'

# The full version, including alpha/beta/rc tags
release = '1.0'

# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.ext.autosummary',
    'sphinx_rtd_theme',  # Read the Docs theme
]

autosummary_generate = True  # Automatically create summaries

templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Use 'en' or 'fr' for bilingual docs.
language = 'en'

# List of patterns, relative to source directory, that match files and directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']

# -- Handling of Read the Docs environment -----------------------------------

# Use the special output directory for Read the Docs if detected
if os.environ.get('READTHEDOCS') == 'True':
    html_output_dir = os.environ.get('READTHEDOCS_OUTPUT', '_build/html')
else:
    html_output_dir = '_build/html'

# -- Internationalization settings -------------------------------------------

locale_dirs = ['locale/']  # Path to the translations
gettext_compact = False

# -- Autodoc settings --------------------------------------------------------

autodoc_mock_imports = ['lumache']  # Mock 'lumache' module if not available
autodoc_default_options = {
    'members': True,
    'undoc-members': True,
    'private-members': True,
    'special-members': '__init__',
    'show-inheritance': True,
}

# -- Napoleon settings (for Google and NumPy style docstrings) ---------------

napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True

# -- Todo extension settings -------------------------------------------------

todo_include_todos = True
